Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace MyRestService

    Partial Public Class TestDataEntities
        Inherits DbContext

        Public Sub New()
            MyBase.New("name=TestDataConnectionString")
        End Sub

        Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
            'throw new UnintentionalCodeFirstException();
        End Sub

        Public Property Categories() As DbSet(Of Category)
    End Class
End Namespace
