Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace MyRestService
    Partial Public Class Category
        Public Property CategoryID() As Integer
        Public Property CategoryName() As String
        Public Property RegisterDate() As DateTime
        Public Property Count As Integer
        Public Property Price As Decimal
    End Class
End Namespace
